/**
 * Discrete Dialog IR — Phase 36 (2026-06-05). Imperative dialog API.
 *
 * Centered overlay dialog with a semi-transparent mask. Named
 * `discrete-dialog` (not `dialog`) to avoid confusion with the Phase 27
 * modal-based dialog. Core IR ships the pure-data types, class-list
 * helper, CSS, and a counter-based ID generator.
 *
 * Public surface:
 *
 * - **`DialogType`** — `'info' | 'success' | 'warning' | 'error' | 'default'`.
 * - **`DialogItem`** — immutable dialog item.
 */

/** Semantic type — drives icon + color variant. */
export type DialogType = 'info' | 'success' | 'warning' | 'error' | 'default';

/**
 * Immutable dialog item. Created by the adapter from user options;
 * the core never mutates items.
 */
export interface DialogItem {
  /** Unique identifier generated by `createDialogItemId`. */
  readonly id: string;
  /** Optional title text. */
  readonly title?: string | undefined;
  /** Body content text. */
  readonly content: string;
  /** Semantic type. */
  readonly type: DialogType;
  /** Text for the positive (confirm) button. */
  readonly positiveText?: string | undefined;
  /** Text for the negative (cancel) button. */
  readonly negativeText?: string | undefined;
  /** Whether the user can close via the top-right X button. */
  readonly closable: boolean;
}
