/**
 * Notification IR — Phase 36 (2026-06-05). Imperative notification API.
 *
 * Card-like notifications rendered at fixed corner positions on the
 * viewport. Richer than Message (has title + optional description).
 * Core IR ships the pure-data types, class-list helper, CSS, and a
 * counter-based ID generator.
 *
 * Public surface:
 *
 * - **`NotificationType`** — `'info' | 'success' | 'warning' | 'error'`.
 * - **`NotificationPlacement`** — `'top-right' | 'top-left' | 'bottom-right' | 'bottom-left'`.
 * - **`NotificationItem`** — immutable notification item.
 */

/** Semantic type — drives icon + color variant. */
export type NotificationType = 'info' | 'success' | 'warning' | 'error';

/** Placement of the notification container on the viewport. */
export type NotificationPlacement = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';

/**
 * Immutable notification item. Created by the adapter from user options;
 * the core never mutates items.
 */
export interface NotificationItem {
  /** Unique identifier generated by `createNotificationItemId`. */
  readonly id: string;
  /** Title text (always visible). */
  readonly title: string;
  /** Optional description text below the title. */
  readonly description?: string | undefined;
  /** Semantic type. */
  readonly type: NotificationType;
  /** Auto-dismiss delay in ms. `0` means persistent. */
  readonly duration: number;
  /** Whether the user can manually close the notification. */
  readonly closable: boolean;
}
