/**
 * @chronixjs/table-react — React 18 adapter for the chronix-table core.
 *
 * Phase 0 (2026-05-23): package skeleton.
 * Phase 48 (2026-05-25): first rendering surface — `<ChronixTable>`
 * SFC + `useTableLayout` + `useTableContainerSize` hooks. vue3 Phase 2
 * architectural equivalent.
 * Phase 48.1 (2026-05-25): mechanical-port tail — vue3 Phase 3+4+5+5.1
 * +6+7 consolidated. Adds rowLayoutPass + virtualRowsPass to
 * useTableLayout; adds `useTableBodyScroll` hook; cell value
 * resolution via getCellValue / formatCellValue / resolveCellClassNames;
 * theme CSS-var injection via cssVarsForTheme; 8 callback props
 * (cell+row click/hover + header click + dblclick + empty-area-click)
 * via delegated handlers.
 *
 * Subsequent react sub-phases (49 / 49.1 / 50 / ...) port vue3 Phase
 * 8+ behaviors progressively.
 */

export {
  ChronixTable,
  type CellClickPayload,
  type CellDblclickPayload,
  type CellEditStartPayload,
  type CellEditStopPayload,
  type CellRangeChangePayload,
  type CellRangeCopyPayload,
  type CellRangeFillChangePayload,
  type CellRangeFillPayload,
  type CellRangeFillStartPayload,
  type CellRangePastePayload,
  type CellRangeStartPayload,
  type CellRangeStopPayload,
  type HistoryChangePayload,
  type HistoryReplayPayload,
  type CellValueChangePayload,
  type ChronixTableProps,
  type ColumnMoveStartPayload,
  type ColumnMoveStopPayload,
  type ColumnMoving,
  type ColumnOrderChangePayload,
  type ColumnResizeStartPayload,
  type ColumnResizeStopPayload,
  type ColumnResizing,
  type AdapterXlsxSheetSpec,
  type ColumnVisibilityChangePayload,
  type ColumnWidthChangePayload,
  type ColumnsChangePayload,
  type TableHandleExportToXlsxOptions,
  type ActiveCellChangePayload,
  type EditingCell,
  type EmptyAreaClickPayload,
  type FilterChangePayload,
  type HeaderClickPayload,
  type HeaderGroupClickPayload,
  type PageChangePayload,
  type PendingColumnMove,
  type PendingRowMove,
  type QuickFindTextChangePayload,
  type RowDragColumnConfig,
  type RowMoveStartPayload,
  type RowMoveStopPayload,
  type RowMoving,
  type RowOrderChangePayload,
  type RowClickPayload,
  type RowDblclickPayload,
  type RowMouseenterPayload,
  type RowMouseleavePayload,
  type SelectionChangePayload,
  type SelectionColumnConfig,
  type SortChangePayload,
  type TableHandle,
} from './chronix-table.js';
export {
  useTableLayout,
  type UseTableLayoutInput,
  type UseTableLayoutOutput,
} from './use-table-layout.js';
export { useTableContainerSize, type TableContainerSize } from './use-table-container-size.js';
export { useTableBodyScroll, type TableBodyScroll } from './use-table-body-scroll.js';

// Re-export-through of core IR + theme types so consumers can import
// everything from `@chronixjs/table-react` without a separate
// `@chronixjs/table` import. Matches the chronix-table-vue3 / vue2
// adapters' re-export-through precedent.
export type {
  CellComparatorArgs,
  CellRange,
  CellRangeEnvelope,
  CellRef,
  CellRenderArgs,
  CellValueArgs,
  ChronixTableTheme,
  CoerceEditDraftValueOk,
  CoerceEditDraftValueRejected,
  CoerceEditDraftValueResult,
  ColumnDropTarget,
  ColumnHeaderRect,
  GetColumnDropTargetOptions,
  ColumnLayoutInput,
  ColumnLayoutResult,
  CollectUniqueColumnValuesInput,
  CollectUniqueColumnValuesResult,
  ColumnSpec,
  ColumnTable,
  ColumnUniqueValue,
  ComputeAutosizeWidthOptions,
  EvaluateFilterExpressionContext,
  ExpressionAndNode,
  ExpressionCompareNode,
  ExpressionFilterSpec,
  ExpressionNotNode,
  ExpressionOperator,
  ExpressionOrNode,
  ExpressionScalar,
  ExpressionValue,
  FilterExpression,
  FilterPassInput,
  FilterPassResult,
  FilterSpec,
  MultiFilterEntry,
  ParseFilterExpressionError,
  ParseFilterExpressionOptions,
  ParseFilterExpressionResult,
  RowDropTarget,
  RowRect,
  GetRowDropTargetOptions,
  SetFilterSpec,
  FindNextEditableCellResult,
  FormatCellRangeForClipboardOptions,
  MutationBatch,
  MutationHistoryState,
  PasteMutation,
  HeaderCell,
  NumberFilterOperator,
  NumberFilterSpec,
  PagePassInput,
  PagePassResult,
  PinnedColsInput,
  PinnedColsResult,
  RowAction,
  RowDataSource,
  BlockState,
  ToolPanelChangePayload,
  ToolPanelConfig,
  ToolPanelDescriptor,
  ToolPanelRenderer,
  ToolPanelWidthChangePayload,
  ContextMenuConfig,
  ContextMenuContext,
  ContextMenuItem,
  ContextMenuOpenPayload,
  CreateServerSideRowSourceOptions,
  GetRowsParams,
  GetRowsResult,
  ServerSideDataSource,
  ServerSideRowSource,
  ServerSideViewParams,
  RowLayoutInput,
  RowLayoutResult,
  RowSpec,
  SortSpec,
  BuildXlsxSheetDataInput,
  BuildXlsxSheetDataResult,
  ExportToXlsxInput,
  ExportToXlsxOptions,
  FormatActiveCellAnnouncementInput,
  MultiSheetExportToXlsxInput,
  SingleSheetExportToXlsxInput,
  XlsxCellValue,
  TableViewApplyResult,
  TableViewColumnState,
  TableViewState,
  TextFilterOperator,
  TextFilterSpec,
  VirtualRowsInput,
  VirtualRowsResult,
  VisiblePageElement,
} from '@chronixjs/table';
export {
  applyTableView,
  buildXlsxSheetData,
  clampResizeWidth,
  coerceEditDraftValue,
  columnLayoutPass,
  computeAutosizeWidth,
  computeCellRangeEnvelope,
  appendMutationBatch,
  computeColumnReorder,
  computeRowReorder,
  computeDragFillEnvelope,
  computeDragFillMutations,
  computePasteMutations,
  computeRangeRowIds,
  computeVisiblePageNumbers,
  createClientSideRowSource,
  createColumnTable,
  createServerSideRowSource,
  DEFAULT_TOOL_PANEL_MAX_WIDTH_PX,
  DEFAULT_TOOL_PANEL_MIN_WIDTH_PX,
  DEFAULT_TOOL_PANEL_WIDTH_PX,
  TOOL_PANEL_ICON_RAIL_WIDTH_PX,
  BLOCK_KIND_ERROR,
  BLOCK_KIND_IDLE,
  BLOCK_KIND_LOADED,
  BLOCK_KIND_LOADING,
  DEFAULT_CACHE_BLOCK_SIZE,
  DEFAULT_SERVER_SIDE_MAX_BLOCKS_IN_CACHE,
  SERVER_SIDE_SKELETON_ID_PREFIX,
  isServerSideSkeletonRowId,
  cssVarsForTheme,
  DEFAULT_COLUMN_MOVE_DRAG_THRESHOLD_PX,
  DEFAULT_ROW_DRAG_THRESHOLD_PX,
  defaultChronixTableTheme,
  defaultFormatCellValue,
  EMPTY_CELL_RANGE_ENVELOPE,
  EMPTY_MUTATION_HISTORY,
  EMPTY_PINNED_COLS_RESULT,
  filterPass,
  findNextEditableCell,
  formatCellRangeForClipboard,
  formatCellValue,
  formatPrefixNumberFilter,
  getCellValue,
  getColumnDropTarget,
  getRowDropTarget,
  buildExpressionPredicate,
  collectUniqueColumnValues,
  expressionReferencesValidColumns,
  pagePass,
  parseClipboardTsv,
  parseFilterExpression,
  parsePrefixNumberFilter,
  pinnedColsPass,
  popRedoBatch,
  popUndoBatch,
  exportToXlsx,
  formatActiveCellAnnouncement,
  resolveCellClassNames,
  reverseMutationBatch,
  rowLayoutPass,
  serializeTableView,
  sortPass,
  virtualRowsPass,
} from '@chronixjs/table';

export {
  ChronixColumnsToolPanel,
  type ChronixColumnsToolPanelProps,
} from './chronix-columns-tool-panel.js';
export {
  ChronixFiltersToolPanel,
  type ChronixFiltersToolPanelProps,
  formatFilterChipLabel,
} from './chronix-filters-tool-panel.js';

export const TABLE_REACT_PACKAGE_VERSION = '0.1.0-alpha.0';
