/**
 * @chronixjs/table-vue2 — Vue 2.7 adapter for the chronix-table core.
 *
 * package skeleton.
 * first rendering surface — `<ChronixTable>`
 * SFC + `useTableLayout` + `useTableContainerSize` composables.
 * Verbatim port of chronix-table-vue3's form (commit
 * `3518eb7`). Vue 2.7's composition API surface is identical to
 * Vue 3 for everything uses; deltas are limited to the
 * `ctx.expose` call shape + the local `toValue` / `MaybeRefOrGetter`
 * shim (Vue 2.7 predates Vue 3.3's helpers).
 *
 * Subsequent vue2 sub-phases (41.1 / 41.2 / 42 / 43 / ...) port
 * vue3 + behaviors progressively.
 */

export {
  ChronixTable,
  type CellClickPayload,
  type CellDblclickPayload,
  type CellEditStartPayload,
  type CellEditStopPayload,
  type CellRangeChangePayload,
  type CellRangeCopyPayload,
  type CellRangeFillChangePayload,
  type CellRangeFillPayload,
  type CellRangeFillStartPayload,
  type CellRangePastePayload,
  type CellRangeStartPayload,
  type CellRangeStopPayload,
  type HistoryChangePayload,
  type HistoryReplayPayload,
  type CellValueChangePayload,
  type ColumnMoveStartPayload,
  type ColumnMoveStopPayload,
  type ColumnMoving,
  type ColumnOrderChangePayload,
  type ColumnResizeStartPayload,
  type ColumnResizeStopPayload,
  type ColumnResizing,
  type AdapterXlsxSheetSpec,
  type ColumnVisibilityChangePayload,
  type ColumnWidthChangePayload,
  type ColumnsChangePayload,
  type TableHandleExportToXlsxOptions,
  type ActiveCellChangePayload,
  type EditingCell,
  type EmptyAreaClickPayload,
  type FilterChangePayload,
  type HeaderClickPayload,
  type HeaderGroupClickPayload,
  type PageChangePayload,
  type PendingColumnMove,
  type PendingRowMove,
  type QuickFindTextChangePayload,
  type RowDragColumnConfig,
  type RowMoveStartPayload,
  type RowMoveStopPayload,
  type RowMoving,
  type RowOrderChangePayload,
  type RowClickPayload,
  type RowDblclickPayload,
  type RowMouseenterPayload,
  type RowMouseleavePayload,
  type SelectionChangePayload,
  type SelectionColumnConfig,
  type SortChangePayload,
  type TableHandle,
} from './chronix-table.js';
export {
  useTableLayout,
  type MaybeRefOrGetter,
  type UseTableLayoutInput,
  type UseTableLayoutOutput,
} from './use-table-layout.js';
export { useTableContainerSize, type TableContainerSize } from './use-table-container-size.js';

// Re-export-through of core IR + theme types so consumers can import
// everything from `@chronixjs/table-vue2` without a separate
// `@chronixjs/table` import. Matches the chronix-table-vue3 adapter's
// re-export-through precedent.
export type {
  CellComparatorArgs,
  CellRange,
  CellRangeEnvelope,
  CellRef,
  CellRenderArgs,
  CellValueArgs,
  ChronixTableTheme,
  ColumnDropTarget,
  ColumnHeaderRect,
  GetColumnDropTargetOptions,
  ColumnLayoutInput,
  ColumnLayoutResult,
  CollectUniqueColumnValuesInput,
  CollectUniqueColumnValuesResult,
  ColumnSpec,
  ColumnTable,
  ColumnUniqueValue,
  CoerceEditDraftValueOk,
  CoerceEditDraftValueRejected,
  CoerceEditDraftValueResult,
  ComputeAutosizeWidthOptions,
  EvaluateFilterExpressionContext,
  ExpressionAndNode,
  ExpressionCompareNode,
  ExpressionFilterSpec,
  ExpressionNotNode,
  ExpressionOperator,
  ExpressionOrNode,
  ExpressionScalar,
  ExpressionValue,
  FilterExpression,
  FilterPassInput,
  FilterPassResult,
  FilterSpec,
  MultiFilterEntry,
  ParseFilterExpressionError,
  ParseFilterExpressionOptions,
  ParseFilterExpressionResult,
  RowDropTarget,
  RowRect,
  GetRowDropTargetOptions,
  SetFilterSpec,
  FindNextEditableCellResult,
  FormatCellRangeForClipboardOptions,
  MutationBatch,
  MutationHistoryState,
  PasteMutation,
  HeaderCell,
  NumberFilterOperator,
  NumberFilterSpec,
  PinnedColsInput,
  PinnedColsResult,
  RowAction,
  RowDataSource,
  BlockState,
  ToolPanelChangePayload,
  ToolPanelConfig,
  ToolPanelDescriptor,
  ToolPanelRenderer,
  ToolPanelWidthChangePayload,
  ContextMenuConfig,
  ContextMenuContext,
  ContextMenuItem,
  ContextMenuOpenPayload,
  CreateServerSideRowSourceOptions,
  GetRowsParams,
  GetRowsResult,
  ServerSideDataSource,
  ServerSideRowSource,
  ServerSideViewParams,
  RowLayoutInput,
  RowLayoutResult,
  RowSpec,
  SortSpec,
  BuildXlsxSheetDataInput,
  BuildXlsxSheetDataResult,
  ExportToXlsxInput,
  ExportToXlsxOptions,
  FormatActiveCellAnnouncementInput,
  MultiSheetExportToXlsxInput,
  SingleSheetExportToXlsxInput,
  XlsxCellValue,
  TableViewApplyResult,
  TableViewColumnState,
  TableViewState,
  TextFilterOperator,
  TextFilterSpec,
  VisiblePageElement,
} from '@chronixjs/table';
export {
  applyTableView,
  buildXlsxSheetData,
  clampResizeWidth,
  coerceEditDraftValue,
  columnLayoutPass,
  computeAutosizeWidth,
  computeCellRangeEnvelope,
  appendMutationBatch,
  computeColumnReorder,
  computeRowReorder,
  computeDragFillEnvelope,
  computeDragFillMutations,
  computePasteMutations,
  computeRangeRowIds,
  computeVisiblePageNumbers,
  createClientSideRowSource,
  createColumnTable,
  createServerSideRowSource,
  DEFAULT_TOOL_PANEL_MAX_WIDTH_PX,
  DEFAULT_TOOL_PANEL_MIN_WIDTH_PX,
  DEFAULT_TOOL_PANEL_WIDTH_PX,
  TOOL_PANEL_ICON_RAIL_WIDTH_PX,
  BLOCK_KIND_ERROR,
  BLOCK_KIND_IDLE,
  BLOCK_KIND_LOADED,
  BLOCK_KIND_LOADING,
  DEFAULT_CACHE_BLOCK_SIZE,
  DEFAULT_SERVER_SIDE_MAX_BLOCKS_IN_CACHE,
  SERVER_SIDE_SKELETON_ID_PREFIX,
  isServerSideSkeletonRowId,
  cssVarsForTheme,
  DEFAULT_COLUMN_MOVE_DRAG_THRESHOLD_PX,
  DEFAULT_ROW_DRAG_THRESHOLD_PX,
  defaultChronixTableTheme,
  defaultFormatCellValue,
  EMPTY_CELL_RANGE_ENVELOPE,
  EMPTY_MUTATION_HISTORY,
  EMPTY_PINNED_COLS_RESULT,
  filterPass,
  findNextEditableCell,
  formatCellRangeForClipboard,
  formatCellValue,
  formatPrefixNumberFilter,
  getCellValue,
  getColumnDropTarget,
  getRowDropTarget,
  buildExpressionPredicate,
  collectUniqueColumnValues,
  expressionReferencesValidColumns,
  pagePass,
  parseClipboardTsv,
  parseFilterExpression,
  parsePrefixNumberFilter,
  pinnedColsPass,
  popRedoBatch,
  popUndoBatch,
  exportToXlsx,
  formatActiveCellAnnouncement,
  resolveCellClassNames,
  reverseMutationBatch,
  serializeTableView,
  sortPass,
} from '@chronixjs/table';

export {
  ChronixColumnsToolPanel,
  type ChronixColumnsToolPanelProps,
} from './chronix-columns-tool-panel.js';
export {
  ChronixFiltersToolPanel,
  type ChronixFiltersToolPanelProps,
  formatFilterChipLabel,
} from './chronix-filters-tool-panel.js';

export const TABLE_VUE2_PACKAGE_VERSION = '0.1.0-alpha.0';
