/**
 * Message IR — . Imperative toast API.
 *
 * Lightweight inline notifications rendered at fixed positions on the
 * viewport. Each message is an item in a queue managed by the adapter.
 * Core IR ships the pure-data types, class-list helper, CSS, and a
 * counter-based ID generator.
 *
 * Public surface:
 *
 * - **`MessageType`** — `'info' | 'success' | 'warning' | 'error' | 'loading'`.
 * - **`MessagePlacement`** — `'top' | 'top-right' | 'bottom' | 'bottom-right'`.
 * - **`MessageItem`** — immutable queue item.
 * - **`MessageQueueOptions`** — queue configuration.
 */

/** Semantic type — drives icon + color variant. */
export type MessageType = 'info' | 'success' | 'warning' | 'error' | 'loading';

/** Placement of the message container on the viewport. */
export type MessagePlacement = 'top' | 'top-right' | 'bottom' | 'bottom-right';

/**
 * Immutable item in the message queue. Created by the adapter from user
 * options; the core never mutates items.
 */
export interface MessageItem {
  /** Unique identifier generated by `createMessageItemId`. */
  readonly id: string;
  /** Text content of the message. */
  readonly content: string;
  /** Semantic type. */
  readonly type: MessageType;
  /** Auto-dismiss delay in ms. `0` means persistent (no auto-dismiss). */
  readonly duration: number;
  /** Whether the user can manually close the message. */
  readonly closable: boolean;
}

/**
 * Configuration for the message queue (max count, placement, default
 * duration).
 */
export interface MessageQueueOptions {
  /** Maximum number of visible messages. `undefined` = unlimited. */
  readonly max?: number | undefined;
  /** Where messages appear on screen. Default `'top'`. */
  readonly placement?: MessagePlacement | undefined;
  /** Default auto-dismiss duration in ms. `0` = persistent. */
  readonly duration?: number | undefined;
}
