import { defineConfig } from 'vitepress';
import { resolve } from 'path';

export default defineConfig({
  base: '/chronixjs/',
  head: [['link', { rel: 'icon', href: '/chronixjs/favicon.ico' }]],
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: true,

  vite: {
    resolve: {
      alias: {
        '@chronixjs/ui-vue3': resolve(__dirname, '../../adapters/ui-vue3/src/index.ts'),
        '@chronixjs/ui': resolve(__dirname, '../../packages/ui/src/index.ts'),
        '@chronixjs/gantt-vue3': resolve(__dirname, '../../adapters/gantt-vue3/src/index.ts'),
        '@chronixjs/gantt': resolve(__dirname, '../../packages/gantt/src/index.ts'),
        '@chronixjs/table-vue3': resolve(__dirname, '../../adapters/table-vue3/src/index.ts'),
        '@chronixjs/table': resolve(__dirname, '../../packages/table/src/index.ts'),
      },
    },
  },

  locales: {
    root: {
      lang: 'zh-CN',
      label: '简体中文',
      title: 'Chronix',
      description: '框架无关的组件库 — 甘特图、表格、UI 组件、CX Kit',
    },
    en: {
      lang: 'en-US',
      label: 'English',
      title: 'Chronix',
      description: 'Framework-agnostic component library — Gantt, Table, UI, CX Kit',
    },
  },

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'Chronix',

    locales: {
      root: {
        nav: [
          { text: '指南', link: '/getting-started/installation' },
          { text: '甘特图', link: '/gantt/' },
          { text: '表格', link: '/table/' },
          { text: 'UI 组件', link: '/ui/' },
          { text: 'CX Kit', link: '/cx-kit/' },
          {
            text: 'v0.1 (alpha)',
            items: [
              { text: 'GitHub', link: 'https://github.com/liaoyu1992/chronixjs' },
              { text: 'npm', link: 'https://www.npmjs.com/org/chronixjs' },
            ],
          },
        ],

        sidebar: {
          '/gantt/': [
            { text: '概览', link: '/gantt/' },
            { text: '快速开始', link: '/gantt/getting-started' },
            {
              text: '功能',
              collapsed: false,
              items: [
                { text: '任务条', link: '/gantt/bars' },
                { text: '连线与依赖', link: '/gantt/links' },
                { text: '时间线视图', link: '/gantt/views' },
                { text: '主题', link: '/gantt/theme' },
              ],
            },
            {
              text: 'API 参考',
              link: '/gantt/api',
            },
          ],
          '/table/': [
            { text: '概览', link: '/table/' },
            { text: '快速开始', link: '/table/getting-started' },
            {
              text: '功能',
              collapsed: false,
              items: [
                { text: '列', link: '/table/columns' },
                { text: '行与数据', link: '/table/rows' },
                { text: '排序', link: '/table/sorting' },
                { text: '筛选', link: '/table/filtering' },
                { text: '行内编辑', link: '/table/editing' },
                { text: '树形数据', link: '/table/tree-data' },
                { text: '固定列/行', link: '/table/pinned' },
                { text: '导出 (CSV)', link: '/table/export' },
                { text: '主题', link: '/table/theme' },
              ],
            },
            { text: 'API 参考', link: '/table/api' },
          ],
          '/ui/': [
            { text: '概览', link: '/ui/' },
            { text: '快速开始', link: '/ui/getting-started' },
            { text: '主题系统', link: '/ui/theme' },
            {
              text: '组件',
              collapsed: false,
              items: [
                { text: 'Affix 固钉', link: '/ui/components/affix' },
                { text: 'Alert 警告', link: '/ui/components/alert' },
                { text: 'Anchor 锚点', link: '/ui/components/anchor' },
                { text: 'Autocomplete 自动补全', link: '/ui/components/auto-complete' },
                { text: 'Avatar 头像', link: '/ui/components/avatar' },
                { text: 'Avatar Group 头像组', link: '/ui/components/avatar-group' },
                { text: 'Back Top 回到顶部', link: '/ui/components/back-top' },
                { text: 'Badge 徽标', link: '/ui/components/badge' },
                { text: 'Breadcrumb 面包屑', link: '/ui/components/breadcrumb' },
                { text: 'Button 按钮', link: '/ui/components/button' },
                { text: 'Button Group 按钮组', link: '/ui/components/button-group' },
                { text: 'Calendar 日历', link: '/ui/components/calendar' },
                { text: 'Card 卡片', link: '/ui/components/card' },
                { text: 'Carousel 走马灯', link: '/ui/components/carousel' },
                { text: 'Cascader 级联选择', link: '/ui/components/cascader' },
                { text: 'Checkbox 复选框', link: '/ui/components/checkbox' },
                { text: 'Code 代码', link: '/ui/components/code' },
                { text: 'Collapse 折叠面板', link: '/ui/components/collapse' },
                {
                  text: 'Collapse Transition 折叠过渡',
                  link: '/ui/components/collapse-transition',
                },
                { text: 'Color Picker 颜色选择器', link: '/ui/components/color-picker' },
                { text: 'Countdown 倒计时', link: '/ui/components/countdown' },
                { text: 'Date Picker 日期选择器', link: '/ui/components/date-picker' },
                { text: 'Descriptions 描述列表', link: '/ui/components/descriptions' },
                { text: 'Dialog 对话框', link: '/ui/components/dialog' },
                { text: 'Divider 分割线', link: '/ui/components/divider' },
                { text: 'Drawer 抽屉', link: '/ui/components/drawer' },
                { text: 'Dropdown 下拉菜单', link: '/ui/components/dropdown' },
                { text: 'Dynamic Input 动态输入', link: '/ui/components/dynamic-input' },
                { text: 'Dynamic Tags 动态标签', link: '/ui/components/dynamic-tags' },
                { text: 'Element 元素', link: '/ui/components/element' },
                { text: 'Ellipsis 省略', link: '/ui/components/ellipsis' },
                { text: 'Empty 空状态', link: '/ui/components/empty' },
                { text: 'Equation 等式', link: '/ui/components/equation' },
                { text: 'Flex 弹性布局', link: '/ui/components/flex' },
                { text: 'Float Button 浮动按钮', link: '/ui/components/float-button' },
                { text: 'Form 表单', link: '/ui/components/form' },
                { text: 'Gradient Text 渐变文字', link: '/ui/components/gradient-text' },
                { text: 'Grid 栅格', link: '/ui/components/grid' },
                { text: 'Heatmap 热力图', link: '/ui/components/heatmap' },
                { text: 'Highlight 高亮', link: '/ui/components/highlight' },
                { text: 'Icon 图标', link: '/ui/components/icon' },
                { text: 'Icon Wrapper 图标容器', link: '/ui/components/icon-wrapper' },
                { text: 'Image 图片', link: '/ui/components/image' },
                { text: 'Input 输入框', link: '/ui/components/input' },
                { text: 'Input Number 数字输入框', link: '/ui/components/input-number' },
                { text: 'Input OTP 验证码输入', link: '/ui/components/input-otp' },
                { text: 'Infinite Scroll 无限滚动', link: '/ui/components/infinite-scroll' },
                { text: 'Layout 布局', link: '/ui/components/layout' },
                { text: 'List 列表', link: '/ui/components/list' },
                { text: 'Loading Bar 加载条', link: '/ui/components/loading-bar' },
                { text: 'Log 日志', link: '/ui/components/log' },
                { text: 'Marquee 跑马灯', link: '/ui/components/marquee' },
                { text: 'Mention 提及', link: '/ui/components/mention' },
                { text: 'Menu 菜单', link: '/ui/components/menu' },
                { text: 'Message 消息', link: '/ui/components/message' },
                { text: 'Modal 模态框', link: '/ui/components/modal' },
                { text: 'Notification 通知', link: '/ui/components/notification' },
                { text: 'Number Animation 数字动画', link: '/ui/components/number-animation' },
                { text: 'Page Header 页头', link: '/ui/components/page-header' },
                { text: 'Pagination 分页', link: '/ui/components/pagination' },
                { text: 'Popconfirm 弹出确认', link: '/ui/components/popconfirm' },
                { text: 'Pop Select 弹出选择', link: '/ui/components/pop-select' },
                { text: 'Popover 气泡弹出', link: '/ui/components/popover' },
                { text: 'Progress 进度条', link: '/ui/components/progress' },
                { text: 'QR Code 二维码', link: '/ui/components/qrcode' },
                { text: 'Radio 单选', link: '/ui/components/radio' },
                { text: 'Rate 评分', link: '/ui/components/rate' },
                { text: 'Result 结果', link: '/ui/components/result' },
                { text: 'Scrollbar 滚动条', link: '/ui/components/scrollbar' },
                { text: 'Select 选择器', link: '/ui/components/select' },
                { text: 'Skeleton 骨架屏', link: '/ui/components/skeleton' },
                { text: 'Slider 滑块', link: '/ui/components/slider' },
                { text: 'Space 间距', link: '/ui/components/space' },
                { text: 'Spin 旋转', link: '/ui/components/spin' },
                { text: 'Split 分割', link: '/ui/components/split' },
                { text: 'Statistic 统计数值', link: '/ui/components/statistic' },
                { text: 'Steps 步骤条', link: '/ui/components/steps' },
                { text: 'Switch 开关', link: '/ui/components/switch' },
                { text: 'Tabs 标签页', link: '/ui/components/tabs' },
                { text: 'Tag 标签', link: '/ui/components/tag' },
                { text: 'Time Picker 时间选择器', link: '/ui/components/time-picker' },
                { text: 'Timeline 时间线', link: '/ui/components/timeline' },
                { text: 'Thing 东西', link: '/ui/components/thing' },
                { text: 'Tooltip 提示', link: '/ui/components/tooltip' },
                { text: 'Transfer 穿梭框', link: '/ui/components/transfer' },
                { text: 'Tree 树', link: '/ui/components/tree' },
                { text: 'Tree Select 树选择', link: '/ui/components/tree-select' },
                { text: 'Typography 排版', link: '/ui/components/typography' },
                { text: 'Upload 上传', link: '/ui/components/upload' },
                { text: 'Watermark 水印', link: '/ui/components/watermark' },
                { text: 'Wave 波浪', link: '/ui/components/wave' },
              ],
            },
          ],
          '/cx-kit/': [
            { text: '概览', link: '/cx-kit/' },
            { text: '快速开始', link: '/cx-kit/getting-started' },
            { text: '虚拟列表', link: '/cx-kit/virtual-list' },
            { text: '滑块', link: '/cx-kit/slider' },
            { text: '范围输入', link: '/cx-kit/input-range' },
            { text: '颜色选择器', link: '/cx-kit/color-picker' },
            { text: '自动补全', link: '/cx-kit/autocomplete' },
          ],
        },

        editLink: {
          pattern: 'https://github.com/liaoyu1992/chronixjs/edit/main/docs/:path',
          text: '在 GitHub 上编辑此页',
        },

        footer: {
          message: '基于 MIT 许可发布。',
          copyright: 'Copyright 2024-present liaoyu1992',
        },

        docFooter: {
          prev: '上一页',
          next: '下一页',
        },

        outline: {
          label: '页面导航',
        },

        lastUpdated: {
          text: '最后更新于',
        },

        returnToTopLabel: '回到顶部',
        sidebarMenuLabel: '菜单',
        darkModeSwitchLabel: '主题',
        lightModeSwitchTitle: '切换到浅色模式',
        darkModeSwitchTitle: '切换到深色模式',
      },

      en: {
        nav: [
          { text: 'Guide', link: '/en/getting-started/installation' },
          { text: 'Gantt', link: '/en/gantt/' },
          { text: 'Table', link: '/en/table/' },
          { text: 'UI', link: '/en/ui/' },
          { text: 'CX Kit', link: '/en/cx-kit/' },
          {
            text: 'v0.1 (alpha)',
            items: [
              { text: 'GitHub', link: 'https://github.com/liaoyu1992/chronixjs' },
              { text: 'npm', link: 'https://www.npmjs.com/org/chronixjs' },
            ],
          },
        ],

        sidebar: {
          '/en/gantt/': [
            { text: 'Overview', link: '/en/gantt/' },
            { text: 'Getting Started', link: '/en/gantt/getting-started' },
            {
              text: 'Features',
              collapsed: false,
              items: [
                { text: 'Bars', link: '/en/gantt/bars' },
                { text: 'Links & Dependencies', link: '/en/gantt/links' },
                { text: 'Timeline Views', link: '/en/gantt/views' },
                { text: 'Theme', link: '/en/gantt/theme' },
              ],
            },
            {
              text: 'API Reference',
              link: '/en/gantt/api',
            },
          ],
          '/en/table/': [
            { text: 'Overview', link: '/en/table/' },
            { text: 'Getting Started', link: '/en/table/getting-started' },
            {
              text: 'Features',
              collapsed: false,
              items: [
                { text: 'Columns', link: '/en/table/columns' },
                { text: 'Rows & Data', link: '/en/table/rows' },
                { text: 'Sorting', link: '/en/table/sorting' },
                { text: 'Filtering', link: '/en/table/filtering' },
                { text: 'Inline Editing', link: '/en/table/editing' },
                { text: 'Tree Data', link: '/en/table/tree-data' },
                { text: 'Pinned Columns/Rows', link: '/en/table/pinned' },
                { text: 'Export (CSV)', link: '/en/table/export' },
                { text: 'Theme', link: '/en/table/theme' },
              ],
            },
            { text: 'API Reference', link: '/en/table/api' },
          ],
          '/en/ui/': [
            { text: 'Overview', link: '/en/ui/' },
            { text: 'Getting Started', link: '/en/ui/getting-started' },
            { text: 'Theme System', link: '/en/ui/theme' },
            {
              text: 'Components',
              collapsed: false,
              items: [
                { text: 'Affix', link: '/en/ui/components/affix' },
                { text: 'Alert', link: '/en/ui/components/alert' },
                { text: 'Anchor', link: '/en/ui/components/anchor' },
                { text: 'Autocomplete', link: '/en/ui/components/auto-complete' },
                { text: 'Avatar', link: '/en/ui/components/avatar' },
                { text: 'Avatar Group', link: '/en/ui/components/avatar-group' },
                { text: 'Back Top', link: '/en/ui/components/back-top' },
                { text: 'Badge', link: '/en/ui/components/badge' },
                { text: 'Breadcrumb', link: '/en/ui/components/breadcrumb' },
                { text: 'Button', link: '/en/ui/components/button' },
                { text: 'Button Group', link: '/en/ui/components/button-group' },
                { text: 'Calendar', link: '/en/ui/components/calendar' },
                { text: 'Card', link: '/en/ui/components/card' },
                { text: 'Carousel', link: '/en/ui/components/carousel' },
                { text: 'Cascader', link: '/en/ui/components/cascader' },
                { text: 'Checkbox', link: '/en/ui/components/checkbox' },
                { text: 'Code', link: '/en/ui/components/code' },
                { text: 'Collapse', link: '/en/ui/components/collapse' },
                { text: 'Collapse Transition', link: '/en/ui/components/collapse-transition' },
                { text: 'Color Picker', link: '/en/ui/components/color-picker' },
                { text: 'Countdown', link: '/en/ui/components/countdown' },
                { text: 'Date Picker', link: '/en/ui/components/date-picker' },
                { text: 'Descriptions', link: '/en/ui/components/descriptions' },
                { text: 'Dialog', link: '/en/ui/components/dialog' },
                { text: 'Divider', link: '/en/ui/components/divider' },
                { text: 'Drawer', link: '/en/ui/components/drawer' },
                { text: 'Dropdown', link: '/en/ui/components/dropdown' },
                { text: 'Dynamic Input', link: '/en/ui/components/dynamic-input' },
                { text: 'Dynamic Tags', link: '/en/ui/components/dynamic-tags' },
                { text: 'Element', link: '/en/ui/components/element' },
                { text: 'Ellipsis', link: '/en/ui/components/ellipsis' },
                { text: 'Empty', link: '/en/ui/components/empty' },
                { text: 'Equation', link: '/en/ui/components/equation' },
                { text: 'Flex', link: '/en/ui/components/flex' },
                { text: 'Float Button', link: '/en/ui/components/float-button' },
                { text: 'Form', link: '/en/ui/components/form' },
                { text: 'Gradient Text', link: '/en/ui/components/gradient-text' },
                { text: 'Grid', link: '/en/ui/components/grid' },
                { text: 'Heatmap', link: '/en/ui/components/heatmap' },
                { text: 'Highlight', link: '/en/ui/components/highlight' },
                { text: 'Icon', link: '/en/ui/components/icon' },
                { text: 'Icon Wrapper', link: '/en/ui/components/icon-wrapper' },
                { text: 'Image', link: '/en/ui/components/image' },
                { text: 'Input', link: '/en/ui/components/input' },
                { text: 'Input Number', link: '/en/ui/components/input-number' },
                { text: 'Input OTP', link: '/en/ui/components/input-otp' },
                { text: 'Infinite Scroll', link: '/en/ui/components/infinite-scroll' },
                { text: 'Layout', link: '/en/ui/components/layout' },
                { text: 'List', link: '/en/ui/components/list' },
                { text: 'Loading Bar', link: '/en/ui/components/loading-bar' },
                { text: 'Log', link: '/en/ui/components/log' },
                { text: 'Marquee', link: '/en/ui/components/marquee' },
                { text: 'Mention', link: '/en/ui/components/mention' },
                { text: 'Menu', link: '/en/ui/components/menu' },
                { text: 'Message', link: '/en/ui/components/message' },
                { text: 'Modal', link: '/en/ui/components/modal' },
                { text: 'Notification', link: '/en/ui/components/notification' },
                { text: 'Number Animation', link: '/en/ui/components/number-animation' },
                { text: 'Page Header', link: '/en/ui/components/page-header' },
                { text: 'Pagination', link: '/en/ui/components/pagination' },
                { text: 'Popconfirm', link: '/en/ui/components/popconfirm' },
                { text: 'Pop Select', link: '/en/ui/components/pop-select' },
                { text: 'Popover', link: '/en/ui/components/popover' },
                { text: 'Progress', link: '/en/ui/components/progress' },
                { text: 'QR Code', link: '/en/ui/components/qrcode' },
                { text: 'Radio', link: '/en/ui/components/radio' },
                { text: 'Rate', link: '/en/ui/components/rate' },
                { text: 'Result', link: '/en/ui/components/result' },
                { text: 'Scrollbar', link: '/en/ui/components/scrollbar' },
                { text: 'Select', link: '/en/ui/components/select' },
                { text: 'Skeleton', link: '/en/ui/components/skeleton' },
                { text: 'Slider', link: '/en/ui/components/slider' },
                { text: 'Space', link: '/en/ui/components/space' },
                { text: 'Spin', link: '/en/ui/components/spin' },
                { text: 'Split', link: '/en/ui/components/split' },
                { text: 'Statistic', link: '/en/ui/components/statistic' },
                { text: 'Steps', link: '/en/ui/components/steps' },
                { text: 'Switch', link: '/en/ui/components/switch' },
                { text: 'Tabs', link: '/en/ui/components/tabs' },
                { text: 'Tag', link: '/en/ui/components/tag' },
                { text: 'Time Picker', link: '/en/ui/components/time-picker' },
                { text: 'Timeline', link: '/en/ui/components/timeline' },
                { text: 'Thing', link: '/en/ui/components/thing' },
                { text: 'Tooltip', link: '/en/ui/components/tooltip' },
                { text: 'Transfer', link: '/en/ui/components/transfer' },
                { text: 'Tree', link: '/en/ui/components/tree' },
                { text: 'Tree Select', link: '/en/ui/components/tree-select' },
                { text: 'Typography', link: '/en/ui/components/typography' },
                { text: 'Upload', link: '/en/ui/components/upload' },
                { text: 'Watermark', link: '/en/ui/components/watermark' },
                { text: 'Wave', link: '/en/ui/components/wave' },
              ],
            },
          ],
          '/en/cx-kit/': [
            { text: 'Overview', link: '/en/cx-kit/' },
            { text: 'Getting Started', link: '/en/cx-kit/getting-started' },
            { text: 'Virtual List', link: '/en/cx-kit/virtual-list' },
            { text: 'Slider', link: '/en/cx-kit/slider' },
            { text: 'Input Range', link: '/en/cx-kit/input-range' },
            { text: 'Color Picker', link: '/en/cx-kit/color-picker' },
            { text: 'Autocomplete', link: '/en/cx-kit/autocomplete' },
          ],
        },

        editLink: {
          pattern: 'https://github.com/liaoyu1992/chronixjs/edit/main/docs/:path',
          text: 'Edit this page on GitHub',
        },

        footer: {
          message: 'Released under the MIT License.',
          copyright: 'Copyright 2024-present liaoyu1992',
        },
      },
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/liaoyu1992/chronixjs' }],
    search: {
      provider: 'local',
    },
  },
});
