import { defineConfig } from 'vitepress';

export default defineConfig({
  lang: 'en-US',
  title: 'Chronix',
  description: 'Framework-agnostic component library — Gantt, Table, UI, CX Kit',
  base: '/chronixjs/',
  head: [['link', { rel: 'icon', href: '/chronixjs/favicon.ico' }]],
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: true,

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'Chronix',

    nav: [
      { text: 'Guide', link: '/getting-started/installation' },
      { text: 'Gantt', link: '/gantt/' },
      { text: 'Table', link: '/table/' },
      { text: 'UI', link: '/ui/' },
      { text: 'CX Kit', link: '/cx-kit/' },
      {
        text: 'v0.1 (alpha)',
        items: [
          { text: 'GitHub', link: 'https://github.com/liaoyu1992/chronixjs' },
          { text: 'npm', link: 'https://www.npmjs.com/org/chronixjs' },
        ],
      },
    ],

    sidebar: {
      '/gantt/': [
        { text: 'Overview', link: '/gantt/' },
        { text: 'Getting Started', link: '/gantt/getting-started' },
        {
          text: 'Features',
          collapsed: false,
          items: [
            { text: 'Bars', link: '/gantt/bars' },
            { text: 'Links & Dependencies', link: '/gantt/links' },
            { text: 'Timeline Views', link: '/gantt/views' },
            { text: 'Theme', link: '/gantt/theme' },
          ],
        },
        {
          text: 'API Reference',
          link: '/gantt/api',
        },
      ],
      '/table/': [
        { text: 'Overview', link: '/table/' },
        { text: 'Getting Started', link: '/table/getting-started' },
        {
          text: 'Features',
          collapsed: false,
          items: [
            { text: 'Columns', link: '/table/columns' },
            { text: 'Rows & Data', link: '/table/rows' },
            { text: 'Sorting', link: '/table/sorting' },
            { text: 'Filtering', link: '/table/filtering' },
            { text: 'Inline Editing', link: '/table/editing' },
            { text: 'Tree Data', link: '/table/tree-data' },
            { text: 'Pinned Columns/Rows', link: '/table/pinned' },
            { text: 'Export (CSV)', link: '/table/export' },
            { text: 'Theme', link: '/table/theme' },
          ],
        },
        { text: 'API Reference', link: '/table/api' },
      ],
      '/ui/': [
        { text: 'Overview', link: '/ui/' },
        { text: 'Getting Started', link: '/ui/getting-started' },
        { text: 'Theme System', link: '/ui/theme' },
        {
          text: 'Components',
          collapsed: false,
          items: [
            { text: 'Affix', link: '/ui/components/affix' },
            { text: 'Alert', link: '/ui/components/alert' },
            { text: 'Anchor', link: '/ui/components/anchor' },
            { text: 'Autocomplete', link: '/ui/components/autocomplete' },
            { text: 'Avatar', link: '/ui/components/avatar' },
            { text: 'Avatar Group', link: '/ui/components/avatar-group' },
            { text: 'Back Top', link: '/ui/components/back-top' },
            { text: 'Badge', link: '/ui/components/badge' },
            { text: 'Breadcrumb', link: '/ui/components/breadcrumb' },
            { text: 'Button', link: '/ui/components/button' },
            { text: 'Button Group', link: '/ui/components/button-group' },
            { text: 'Calendar', link: '/ui/components/calendar' },
            { text: 'Card', link: '/ui/components/card' },
            { text: 'Carousel', link: '/ui/components/carousel' },
            { text: 'Cascader', link: '/ui/components/cascader' },
            { text: 'Checkbox', link: '/ui/components/checkbox' },
            { text: 'Code', link: '/ui/components/code' },
            { text: 'Collapse', link: '/ui/components/collapse' },
            { text: 'Collapse Transition', link: '/ui/components/collapse-transition' },
            { text: 'Color Picker', link: '/ui/components/color-picker' },
            { text: 'Countdown', link: '/ui/components/countdown' },
            { text: 'Date Picker', link: '/ui/components/date-picker' },
            { text: 'Descriptions', link: '/ui/components/descriptions' },
            { text: 'Dialog', link: '/ui/components/dialog' },
            { text: 'Divider', link: '/ui/components/divider' },
            { text: 'Drawer', link: '/ui/components/drawer' },
            { text: 'Dropdown', link: '/ui/components/dropdown' },
            { text: 'Dynamic Input', link: '/ui/components/dynamic-input' },
            { text: 'Dynamic Tags', link: '/ui/components/dynamic-tags' },
            { text: 'Element', link: '/ui/components/element' },
            { text: 'Ellipsis', link: '/ui/components/ellipsis' },
            { text: 'Empty', link: '/ui/components/empty' },
            { text: 'Equation', link: '/ui/components/equation' },
            { text: 'Flex', link: '/ui/components/flex' },
            { text: 'Float Button', link: '/ui/components/float-button' },
            { text: 'Form', link: '/ui/components/form' },
            { text: 'Gradient Text', link: '/ui/components/gradient-text' },
            { text: 'Grid', link: '/ui/components/grid' },
            { text: 'Heatmap', link: '/ui/components/heatmap' },
            { text: 'Highlight', link: '/ui/components/highlight' },
            { text: 'Icon', link: '/ui/components/icon' },
            { text: 'Icon Wrapper', link: '/ui/components/icon-wrapper' },
            { text: 'Image', link: '/ui/components/image' },
            { text: 'Input', link: '/ui/components/input' },
            { text: 'Input Number', link: '/ui/components/input-number' },
            { text: 'Input OTP', link: '/ui/components/input-otp' },
            { text: 'Infinite Scroll', link: '/ui/components/infinite-scroll' },
            { text: 'Layout', link: '/ui/components/layout' },
            { text: 'List', link: '/ui/components/list' },
            { text: 'Loading', link: '/ui/components/loading' },
            { text: 'Loading Bar', link: '/ui/components/loading-bar' },
            { text: 'Log', link: '/ui/components/log' },
            { text: 'Marquee', link: '/ui/components/marquee' },
            { text: 'Mention', link: '/ui/components/mention' },
            { text: 'Menu', link: '/ui/components/menu' },
            { text: 'Message', link: '/ui/components/message' },
            { text: 'Modal', link: '/ui/components/modal' },
            { text: 'Notification', link: '/ui/components/notification' },
            { text: 'Number Animation', link: '/ui/components/number-animation' },
            { text: 'Page Header', link: '/ui/components/page-header' },
            { text: 'Pagination', link: '/ui/components/pagination' },
            { text: 'Popconfirm', link: '/ui/components/popconfirm' },
            { text: 'Pop Select', link: '/ui/components/pop-select' },
            { text: 'Popover', link: '/ui/components/popover' },
            { text: 'Progress', link: '/ui/components/progress' },
            { text: 'QR Code', link: '/ui/components/qrcode' },
            { text: 'Radio', link: '/ui/components/radio' },
            { text: 'Rate', link: '/ui/components/rate' },
            { text: 'Result', link: '/ui/components/result' },
            { text: 'Scrollbar', link: '/ui/components/scrollbar' },
            { text: 'Select', link: '/ui/components/select' },
            { text: 'Skeleton', link: '/ui/components/skeleton' },
            { text: 'Slider', link: '/ui/components/slider' },
            { text: 'Space', link: '/ui/components/space' },
            { text: 'Spin', link: '/ui/components/spin' },
            { text: 'Split', link: '/ui/components/split' },
            { text: 'Statistic', link: '/ui/components/statistic' },
            { text: 'Steps', link: '/ui/components/steps' },
            { text: 'Switch', link: '/ui/components/switch' },
            { text: 'Tabs', link: '/ui/components/tabs' },
            { text: 'Tag', link: '/ui/components/tag' },
            { text: 'Time Picker', link: '/ui/components/time-picker' },
            { text: 'Timeline', link: '/ui/components/timeline' },
            { text: 'Thing', link: '/ui/components/thing' },
            { text: 'Tooltip', link: '/ui/components/tooltip' },
            { text: 'Transfer', link: '/ui/components/transfer' },
            { text: 'Tree', link: '/ui/components/tree' },
            { text: 'Tree Select', link: '/ui/components/tree-select' },
            { text: 'Typography', link: '/ui/components/typography' },
            { text: 'Upload', link: '/ui/components/upload' },
            { text: 'Watermark', link: '/ui/components/watermark' },
            { text: 'Wave', link: '/ui/components/wave' },
          ],
        },
      ],
      '/cx-kit/': [
        { text: 'Overview', link: '/cx-kit/' },
        { text: 'Getting Started', link: '/cx-kit/getting-started' },
        { text: 'Virtual List', link: '/cx-kit/virtual-list' },
        { text: 'Slider', link: '/cx-kit/slider' },
        { text: 'Input Range', link: '/cx-kit/input-range' },
        { text: 'Color Picker', link: '/cx-kit/color-picker' },
        { text: 'Autocomplete', link: '/cx-kit/autocomplete' },
      ],
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/liaoyu1992/chronixjs' }],

    editLink: {
      pattern: 'https://github.com/liaoyu1992/chronixjs/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    search: {
      provider: 'local',
    },

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright 2024-present liaoyu1992',
    },
  },
});
