export const VERSION = '0.0.0';

export type {
  AxisGranularity,
  AxisSpec,
  BarProgress,
  BarSpec,
  BarStyleOverrides,
  ChartIR,
  CustomLinkMarker,
  DprIntent,
  LinkMarker,
  LinkRouting,
  LinkSpec,
  RowSpec,
  TimeRange,
  Viewport,
} from './ir/index.js';

export type { BarTable, LinkTable, PendingTransaction, RowDataSource } from './data/index.js';

export type {
  AdvanceBarDragInput,
  AdvanceBarResizeInput,
  AdvanceCalendarRangeSelectInput,
  AdvanceProgressHandleInput,
  AnyTransaction,
  BarDragTransaction,
  BarResizeTransaction,
  BeginBarDragInput,
  BeginBarResizeInput,
  BeginCalendarRangeSelectInput,
  BeginProgressHandleInput,
  CalendarRangeSelectTransaction,
  CommitBarDragInput,
  CommitBarDragOutput,
  CommitBarResizeInput,
  CommitBarResizeOutput,
  CommitCalendarRangeSelectInput,
  CommitCalendarRangeSelectOutput,
  CommitProgressHandleInput,
  CommitProgressHandleOutput,
  PointerCaptureConfig,
  PointerCaptureSession,
  PointerHitResult,
  PointerHitTestInput,
  PointerHitTester,
  PointerPx,
  ProgressHandleTransaction,
  SwimlaneStripResolver,
} from './interaction/index.js';
export {
  defaultPointerCaptureSession,
  defaultPointerHitTester,
  defaultStripResolver,
} from './interaction/index.js';

export type {
  BarSlotArgs,
  IRCanvas,
  PointerOverlayGroup,
  SlotContext,
  SlotRegistry,
  SlotRenderer,
  SlotTemplate,
} from './render/index.js';
export { BAR_SLOT_NAME, createSlotRegistry } from './render/index.js';

export type {
  BarClickPayload,
  BarColorFunc,
  BarDropPayload,
  BarResizePayload,
  BarsSetPayload,
  BarStyleArg,
  ChronixTheme,
  DropProposal,
  EventAllowFunc,
  EventConstraint,
  EventOverlapFunc,
  GanttEventMap,
  GanttHandle,
  GanttOptions,
  IncrementDelta,
  ParseToolbarOptions,
  ProgressChangePayload,
  RejectionReason,
  ResolvedBarStyle,
  ResolveBarStyleInput,
  SelectAllowFunc,
  SelectPayload,
  TodayCellBgOption,
  TodayLineOption,
  ToolbarInput,
  ToolbarModel,
  ToolbarWidget,
  ToolbarWidgetKind,
  ValidationContext,
  ViewChangePayload,
} from './api/index.js';
export {
  applyIncrement,
  defaultChronixTheme,
  formatToolbarTitle,
  nextAnchor,
  parseToolbar,
  prevAnchor,
  resolveBarStyle,
  todayAnchor,
  validateDrop,
  validateResize,
  validateSelect,
} from './api/index.js';

export type {
  AxisHeaderCell,
  AxisHeaderRow,
  AxisRangePlanInput,
  AxisRangePlanner,
  AxisTick,
  BarPlacementPass,
  BarPlacementPassInput,
  BarPlacementPassOutput,
  BarStackHeightPass,
  BarStackHeightPassInput,
  BarStackHeightPassOutput,
  LinkRouter,
  LinkRouterInput,
  LinkRouterOutput,
  PlacedBar,
  PlannedAxis,
  RoutedLink,
  RoutedLinkMarker,
  IndexRange,
  RowSwimlaneLayout,
  RowSwimlaneLayoutInput,
  RowSwimlaneLayoutOutput,
  SwimlaneStrip,
  ViewId,
  VirtualizedPaneLayout,
  VirtualizedPaneLayoutInput,
  VirtualizedPaneLayoutOutput,
  VirtualizedPaneOverscan,
  VirtualizedPaneScroll,
  VirtualizedPaneViewport,
} from './layout/index.js';
export {
  defaultAxisRangePlanner,
  defaultBarPlacementPass,
  defaultBarStackHeightPass,
  defaultLinkRouter,
  defaultRowSwimlaneLayout,
  defaultVirtualizedPaneLayout,
} from './layout/index.js';
