/**
 * @chronixjs/table — framework-agnostic table core.
 *
 * IR-based architecture: framework-agnostic types + pure-function layout
 * passes + chronix-native public API. Adapter packages (vue3 / vue2 /
 * react) wrap the IR with DOM rendering.
 *
 * ships:
 * - IR primitives: `ColumnSpec`, `RowSpec`, `HeaderCell`
 * - Data sources: `ColumnTable`, `RowDataSource` + `createClientSideRowSource`
 * - First layout pass: `columnLayoutPass`
 * - Theme: `ChronixTableTheme` + `defaultChronixTableTheme`
 *
 * Subsequent phases extend per the roadmap in
 * `audit/TABLE_MIGRATION_PLAN.md`.
 */

// IR primitives
export type {
  CellComparatorArgs,
  ColumnSpec,
  EditValidationError,
  RowValidator,
  RowValidationViolation,
  MultiFilterChild,
  MultiFilterChildNumber,
  MultiFilterChildSet,
  MultiFilterChildText,
  MultiFilterEntry,
  MultiFilterGroup,
  MultiFilterSpec,
  RowAction,
  ExpressionAndNode,
  ExpressionCompareNode,
  ExpressionFilterSpec,
  ExpressionNotNode,
  ExpressionOperator,
  ExpressionOrNode,
  ExpressionScalar,
  ExpressionValue,
  FilterExpression,
  FilterSpec,
  HeaderCell,
  NumberFilterOperator,
  NumberFilterSpec,
  RowSpec,
  SetFilterSpec,
  SortSpec,
  TextFilterOperator,
  TextFilterSpec,
  ToolPanelChangePayload,
  ToolPanelConfig,
  ToolPanelDescriptor,
  ToolPanelRenderer,
  ContextMenuConfig,
  ContextMenuContext,
  ContextMenuItem,
  ContextMenuOpenPayload,
} from './ir/index.js';
export {
  computeColumnHeaderMinWidth,
  DEFAULT_TOOL_PANEL_POPOVER_MAX_HEIGHT_PX,
  DEFAULT_TOOL_PANEL_POPOVER_WIDTH_PX,
  normalizeColumnSpec,
  SETTINGS_COLUMN_ID,
  SETTINGS_COLUMN_SPEC,
  withHeaderMinWidth,
} from './ir/index.js';
export type { HeaderMinWidthOptions } from './ir/index.js';

// Data sources
export type { ColumnTable, RowDataSource } from './data/index.js';
export { createClientSideRowSource, createColumnTable } from './data/index.js';

// Layout passes
export type {
  ColumnLayoutInput,
  ColumnLayoutResult,
  FilterPassInput,
  FilterPassResult,
  PagePassInput,
  PagePassResult,
  PinnedColsInput,
  PinnedColsResult,
  PinnedRowsInput,
  PinnedRowsResult,
  QuickFindPassInput,
  QuickFindPassResult,
  RowLayoutInput,
  RowLayoutResult,
  SortPassInput,
  SortPassResult,
  TreeFlattenInput,
  TreeFlattenResult,
  VirtualRowsInput,
  VirtualRowsResult,
} from './layout/index.js';
export {
  columnLayoutPass,
  EMPTY_PINNED_COLS_RESULT,
  filterPass,
  pagePass,
  pinnedColsPass,
  pinnedRowsPass,
  quickFindPass,
  rowLayoutPass,
  sortPass,
  treeFlattenPass,
  virtualRowsPass,
} from './layout/index.js';

// Render helpers
export type { CellValueArgs, CellRenderArgs } from './render/index.js';
export {
  defaultFormatCellValue,
  formatCellValue,
  getCellValue,
  resolveCellClassNames,
} from './render/index.js';

// Public API
export type {
  CellRange,
  CellRangeEnvelope,
  CellRef,
  ChronixTableTheme,
  CoerceEditDraftValueOk,
  CoerceEditDraftValueRejected,
  CoerceEditDraftValueResult,
  RunCellValidatorArgs,
  RunRowValidatorsArgs,
  PasteValidatorGate,
  ColumnDropTarget,
  ColumnHeaderRect,
  GetColumnDropTargetOptions,
  GetRowDropTargetOptions,
  RowDropTarget,
  RowRect,
  ComputeAutosizeWidthOptions,
  FindNextEditableCellResult,
  FormatCellRangeForClipboardOptions,
  HeaderGroupSpan,
  MutationBatch,
  MutationHistoryState,
  CellValueFn,
  DataRegionDirection,
  NavigationDirection,
  PasteMutation,
  ChildrenLoaderArgs,
  ExportToCsvInput,
  ExportToCsvOptions,
  LazyChildrenState,
  LazyChildrenStatus,
  ResolveCellTooltipInput,
  RowSelectionTriState,
  BuildXlsxSheetDataInput,
  BuildXlsxSheetDataResult,
  ExportStyle,
  ExportStyleAlignment,
  ExportStyleBorder,
  ExportStyleFill,
  ExportStyleFont,
  ExportToXlsxFreezePane,
  ExportToXlsxInput,
  ExportToXlsxOptions,
  FormatActiveCellAnnouncementInput,
  FormatColumnHeaderDescriptionInput,
  TextSegment,
  MultiSheetExportToXlsxInput,
  SingleSheetExportToXlsxInput,
  XlsxCellValue,
  CollectUniqueColumnValuesInput,
  CollectUniqueColumnValuesResult,
  ColumnUniqueValue,
  EvaluateFilterExpressionContext,
  ParseFilterExpressionError,
  ParseFilterExpressionOptions,
  ParseFilterExpressionResult,
  SerializeTableViewInput,
  StatusBarCounts,
  SynthesizeLazyChildrenInput,
  SynthesizeLazyChildrenResult,
  DragAutoScrollVelocityInput,
  ScrollIntoViewInput,
  ScrollIntoViewMargins,
  ScrollIntoViewResult,
  ScrollIntoViewTarget,
  ScrollIntoViewViewport,
  TableViewApplyResult,
  TableViewColumnState,
  TableViewState,
  TypeaheadRecentStorage,
  VisiblePageElement,
} from './api/index.js';
export {
  appendMutationBatch,
  applyTableView,
  buildXlsxSheetData,
  clampResizeWidth,
  coerceEditDraftValue,
  collectDescendantRowIds,
  computeAutosizeWidth,
  computeCellRangeEnvelope,
  computeColumnReorder,
  computeRowReorder,
  computeDragFillEnvelope,
  computeDragFillMutations,
  computeFooterValues,
  computeHeaderGroupSpans,
  computeNextActiveCell,
  computePasteMutations,
  computeDragAutoScrollVelocity,
  computeRangeRowIds,
  computeRowSelectionTriState,
  computeScrollIntoView,
  computeVisiblePageNumbers,
  deriveShiftArrowCellRange,
  findDataRegionBoundary,
  cssVarsForTheme,
  DEFAULT_COLUMN_MOVE_DRAG_THRESHOLD_PX,
  DEFAULT_DRAG_AUTO_SCROLL_MAX_VELOCITY_PX_PER_FRAME,
  DEFAULT_DRAG_AUTO_SCROLL_TRIGGER_ZONE_PX,
  DEFAULT_ROW_DRAG_THRESHOLD_PX,
  defaultChronixTableTheme,
  EMPTY_CELL_RANGE_ENVELOPE,
  EMPTY_MUTATION_HISTORY,
  findNextEditableCell,
  formatCellRangeForClipboard,
  formatPrefixNumberFilter,
  getColumnDropTarget,
  getRowDropTarget,
  parseClipboardTsv,
  popRedoBatch,
  popUndoBatch,
  defaultStatusBarText,
  exportToCsv,
  exportToXlsx,
  formatActiveCellAnnouncement,
  formatColumnHeaderDescription,
  splitTextByQuickFindMatch,
  buildExpressionPredicate,
  collectUniqueColumnValues,
  computeColumnNumericExtents,
  createLocalStorageRecentStorage,
  createMemoryRecentStorage,
  DEFAULT_TYPEAHEAD_RECENT_STORAGE_KEY_PREFIX,
  expressionReferencesValidColumns,
  parseFilterExpression,
  resolveCellTooltip,
  reverseMutationBatch,
  parsePrefixNumberFilter,
  runAsyncCellValidator,
  runCellValidator,
  runRowValidators,
  serializeTableView,
  synthesizeLazyChildren,
} from './api/index.js';

export const TABLE_PACKAGE_VERSION = '0.1.0-alpha.0';
